// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication2.Data;

#nullable disable

namespace WebApplication2.Migrations
{
    [DbContext(typeof(WebApplication2Context))]
    [Migration("20231216074852_Test1")]
    partial class Test1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WebApplication2.Model.HeroModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Attackdistance")
                        .HasColumnType("int");

                    b.Property<int>("BasictacticsId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DetachabletacticsId")
                        .HasColumnType("int");

                    b.Property<float>("InitialDefense")
                        .HasColumnType("real");

                    b.Property<float>("InitialStrategy")
                        .HasColumnType("real");

                    b.Property<float>("Initialattack")
                        .HasColumnType("real");

                    b.Property<float>("Initialsiege")
                        .HasColumnType("real");

                    b.Property<float>("Initialspeed")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("armId")
                        .HasColumnType("int");

                    b.Property<float>("costId")
                        .HasColumnType("real");

                    b.Property<int>("groupId")
                        .HasColumnType("int");

                    b.Property<string>("picPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sexId")
                        .HasColumnType("int");

                    b.Property<int>("starId")
                        .HasColumnType("int");

                    b.Property<int>("timeTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HeroModel");
                });

            modelBuilder.Entity("WebApplication2.Model.ProductModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("picPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProductModel");
                });

            modelBuilder.Entity("WebApplication2.Model.SkillModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("armId")
                        .HasColumnType("int");

                    b.Property<int>("quality")
                        .HasColumnType("int");

                    b.Property<int>("target")
                        .HasColumnType("int");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("SkillModel");
                });
#pragma warning restore 612, 618
        }
    }
}
